#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_random_number" test route
app_lucky_number:
  path: /random/number
  controller: App\Controller\DefaultController::number

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }